#!/bin/bash

set -x
set -e

build_squid2radius(){
    apk add py-pip ca-certificates openssl
    pip install pyrad hurry.filesize
    cd /opt
    wget -O- https://github.com/billzhong/squidlog/archive/f1dcaef70eb2aa21253682b1d9c754da784e473b.tar.gz | tar -xzf -
    mv squidlog-* squid2radius
}

apk update
apk add squid squid-lang-zh nghttp2 supervisor tzdata
build_squid2radius
mkdir -p \
    /var/log/supervisor \
    /var/log/nghttpx \
    /var/log/squid

rm -rf /var/cache/apk/*
rm /etc/logrotate.d/squid

sed -i 's/Denied./Denied. Please notice that you can only use light to access TCP 80, 443, 5228 ports./' /usr/share/squid/errors/en/ERR_ACCESS_DENIED
sed -i 's/拒绝。/拒绝。请注意：Light 仅允许访问 TCP 80, 443, 5228 端口。/' /usr/share/squid/errors/zh-hans/ERR_ACCESS_DENIED
